name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $(git describe --tags --abbrev=0) | cut -d . -f1,2).$(( $(echo $(git describe --tags --abbrev=0) | cut -d . -f3) + 1 ))

      - name: Build Docker image
        run: docker build -t your_dockerhub_username/your_image_name:${{ steps.get_version.outputs.VERSION }} .

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your_dockerhub_username/your_image_name:${{ steps.get_version.outputs.VERSION }}
